"""
Init — detects a project's stack and builds a tailored secureaudit.yml.

First-time users shouldn't have to hand-copy secureaudit.yml.example and
guess which plugins apply. This module inspects the target directory for
common manifests/markers and proposes a sensible, minimal plugin set.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import yaml

_LANGUAGE_MANIFESTS: dict[str, list[str]] = {
    "python": ["requirements.txt", "pyproject.toml", "setup.py", "Pipfile"],
    "node": ["package.json"],
    "go": ["go.mod", "go.sum"],
    "rust": ["Cargo.toml"],
    "php": ["composer.json"],
    "ruby": ["Gemfile"],
}


def detect_project(target: Path) -> dict:
    """Inspect target for language manifests, Dockerfile, git, and CI markers."""
    languages = [
        lang for lang, manifests in _LANGUAGE_MANIFESTS.items()
        if any((target / m).exists() for m in manifests)
    ]

    return {
        "languages": languages,
        "has_dockerfile": (target / "Dockerfile").exists() or any(target.glob("Dockerfile.*")),
        "has_git": (target / ".git").exists(),
        "has_ci": (target / ".github" / "workflows").exists(),
    }


def build_config(
    detection: dict,
    urls: list[str] | None = None,
    hosts: list[str] | None = None,
) -> dict:
    """Build a config dict tailored to the detected stack.

    Base plugins (secrets, filesystem, policy) always run — they're fast,
    have no external dependencies, and apply to any repository. Everything
    else is conditional on what was actually detected.
    """
    plugins = ["secrets", "filesystem", "policy"]

    if detection["languages"]:
        plugins.append("cve")

    if detection["has_git"]:
        plugins.append("git_history")

    if detection["has_dockerfile"]:
        plugins.append("trivy")

    cfg: dict = {"plugins": plugins, "fail_below": 70}

    if urls:
        plugins.extend(["http", "cors"])
        cfg["http"] = {"urls": urls}
        cfg["cors"] = {"urls": urls}

    if hosts:
        plugins.append("network")
        cfg["network"] = {"hosts": hosts}

    if detection["has_dockerfile"]:
        cfg["trivy"] = {"timeout": 180, "scan_images": False}

    if detection["has_git"]:
        cfg["git_history"] = {"since_days": 90, "max_commits": 200, "max_findings": 50}

    return cfg


def write_config(path: Path, config: dict) -> None:
    header = (
        f"# Generated by `secureaudit init` on {datetime.now(UTC).date().isoformat()}\n"
        f"# Review and adjust as needed — see secureaudit.yml.example for every option.\n\n"
    )
    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")
